Fixed some typos
jkoelling/trust pull request #1
Opened 2017-09-03 03:41 UTC by stromhalm

Improved German translation

2017-09-03 12:43 UTC, jkoelling requested changes
Hi @stromhalm, vielen Dank für die Korrekturen! Alles was unkommentiert ist, kann so bleiben. Bei den anderen Sachen habe ich erklärt warum ich es so geschrieben habe und gerne so lassen würde. Teilweise gelten die Kommentare auch für unkommentierte Stellen mit. Wäre super wenn du die entsprechenden Änderungen zum pull request hinzufügst, dann merge ich. Nochmals Danke!

2017-09-03 12:43 UTC, jkoelling commented on words.html
> +Also, obwohl du daneben gelegen hast – die freundlichen-aber-naiven <span class="all_c">Immer Kooperieren</span> waren von Anfang an verdammt -- hat sich am Ende eine <i>kluge</i> Art von Freundlichk
Die doppelten Bindestriche sind eigentlich ein [Gedankenstrich](http://www.duden.de/sprachwissen/rechtschreibregeln/gedankenstrich) (-- = –) und fast immer als Einschub mit besonderer Abgrenzung zum restlichen Text gedacht. Deutsch und Englisch unterscheiden sich da nicht wirklich und ich will möglichst nah am Original bleiben in dem auch "--" statt "–" verwendet wird. Daher bitte alle Änderungen an den Strichen zurücknehmen.

2017-09-03 12:43 UTC, jkoelling commented on words.html
> +es muss zumindest möglich sein, dass <i>beide</i> Spieler besser dran sind als ein Win-Win.
Das ändert den Sinn des Satzes. Die Spieler sollen nicht besser dran sein "als ein Win-Win". Das Win-Win ist schon das "besser dran sein". Evtl. klarer mit "…Spieler besser dran sind: ein Win-Win."

2017-09-03 12:43 UTC, jkoelling commented on words.html
> +Es gibt Ansehen, gemeinsame Werte, Verträge, kulturelle Marker und so weiter.
Auch hier wieder: Ich will nah am Original bleiben. Das "blah blah blah" ist in beiden Sprachen sehr umgangsprachlich, aber es ist halt das, was der Autor geschrieben hat.

2017-09-03 12:43 UTC, jkoelling commented on words.html
> +<b>Das Spiel wird durch das Verhalten der Spieler bestimmt.</b><br>
Ich bin auch nicht ganz zufrieden mit meiner Übersetzung, aber deine Version dreht die Bedeutung um. Vorschlag (bei dem auch klar wird, was gemeint ist): "Die Art des Spiels bestimmt das Verhalten der Spieler."

2017-09-03 12:43 UTC, jkoelling commented on words.html
> +Es mag zynisch oder naiv klingen, dass wir "lediglich" Produkte unsere Umwelt sind -
Hier finde ich es ohne "--" auch besser. Dann muss aber auch der "-" hinter sind weg.

2017-09-03 12:43 UTC, jkoelling commented on words.html
> +Dann schaffen wir es, vielleicht, das Feuer einzustellen, aus unseren Gräben zu kommen,
Meins ist näher am Original und das Wort hat weiter vorne mehr Gewicht.

2017-09-03 12:43 UTC, jkoelling commented on words.html
> +Danach, falls du in der letzten Runde kooperiert hast, wiederholt er seinen letzten Zug (auch wenn er ein Versehen war).
"Das Nachäffchen", daher hier und im nächsten Satz "es".

2017-09-10 21:11 UTC, stromhalm commented
Hallo @jkoelling, danke für deine Anmerkungen! Hatte leider die ganze letzte Woche viel zu tun. Habe jetzt aber alle deine Anmerkungen umgesetzt. Schau nochmal, ob's jetzt besser passt. Viele Grüße!

2017-09-20 19:13 UTC, jkoelling approved these changes
Vielen Dank noch mal!

2017-09-20 19:14 UTC, merged